def calcsize(fmt: str) -> int: ...


def pack(fmt: str, *args) -> bytes: ...


def pack_into(fmt: str, buffer: bytearray, offset: int, *args) -> None: ...


def unpack(fmt: str, data: bytes) -> tuple: ...


def unpack_from(fmt: str, buffer: bytearray, offset: int = 0) -> tuple: ...
